# Generated by Django 3.2.5 on 2021-07-30 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='bar_code',
        ),
    ]
