# Generated by Django 3.2.6 on 2021-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_name_product_bar_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
